const THINKERS = [
  {
    id: 'socrates',
    name: 'סוקרטס',
    era: '470–399 לפנה"ס',
    emoji: '🦉',
    image: './images/socrates.webp',
    bio: 'הפילוסוף היווני הגדול שלא כתב דבר אך שינה את פני המחשבה. ידוע בשיטת הדיאלוג והרעיון שהחוכמה האמיתית היא הכרת אי-ידיעתנו.',
    quote: '"הייתי חכם אם ידעתי שאינני יודע דבר."',
  },
  {
    id: 'plato',
    name: 'אפלטון',
    image: './images/plato.webp',
    era: '428–348 לפנה"ס',
    emoji: '🏛',
    bio: 'תלמידו של סוקרטס ומאסטר האלגוריה. פיתח את תורת האידיאות - העולם שאנו רואים הוא רק צל של המציאות האמיתית.',
    quote: '"העיון הפילוסופי הוא שחרור הנשמה מכבלי הגוף."',
  },
  {
    id: 'russell',
    name: 'ברטרנד ראסל',
    image: './images/russell.webp',
    era: '1872–1970',
    emoji: '📐',
    bio: 'פילוסוף בריטי, מתמטיקאי וחתן פרס נובל. ראה בפילוסופיה כלי לבחינה ביקורתית של חיינו ועולמנו, ולחיים בחוסר וודאות.',
    quote: '"הפילוסוף הוא מי שיכול לשאת את חוסר הוודאות."',
  },
  {
    id: 'wittgenstein',
    name: 'ויטגנשטיין',
    image: './images/wittgenstein.webp',
    era: '1889–1951',
    emoji: '🔤',
    bio: 'אחד הפילוסופים המשפיעים של המאה ה-20. טען שגבולות שפתנו הם גבולות עולמנו, ושמרבית הבעיות הפילוסופיות נובעות מבלבול לשוני.',
    quote: '"גבולות שפתי הם גבולות עולמי."',
  },
  {
    id: 'aurelius',
    name: 'מרקוס אורליוס',
    image: './images/aurelius.webp',
    era: '121–180 לספירה',
    emoji: '👑',
    bio: 'קיסר רומי ופילוסוף סטואי. כתב "מחשבות לעצמי" - יומן אישי שהפך לאחד הספרים הנקראים ביותר בעולם - כהדרכה עצמית בחיים טובים.',
    quote: '"האושר בחייך תלוי באיכות מחשבותיך."',
  },
  {
    id: 'aristotle',
    name: 'אריסטו',
    image: './images/aristotle.webp',
    era: '384–322 לפנה"ס',
    emoji: '🌿',
    bio: 'תלמידו של אפלטון שמרד במורהו. יצר את הלוגיקה הפורמלית, חקר את הטבע, המדינה והאתיקה - אחד הרוחות הגדולות בהיסטוריה.',
    quote: '"הפלא הוא ראשיתה של הפילוסופיה."',
  },
  {
    id: 'descartes',
    name: 'דקארט',
    era: '1596–1650',
    image: './images/descartes.webp',
    emoji: '🔭',
    bio: 'אבי הפילוסופיה המודרנית. חיפש בסיס ודאי לכל הידע - ומצא אותו במחשבה עצמה: "אני חושב, משמע אני קיים."',
    quote: '"אני חושב, משמע אני קיים."',
  },
  {
    id: 'kant',
    name: 'עמנואל קאנט',
    era: '1724–1804',
    image: './images/kant.webp',
    emoji: '⚖️',
    bio: 'פילוסוף גרמני שנחשב לאחד הגדולים בכל הזמנים. יצר את הציווי הקטגורי - עיקרון מוסרי אוניברסלי שאינו תלוי בתוצאות אלא בחובה. חי חיים שגרתיים להפליא - הסתובב בקניגסברג יום יום באותה שעה עד שכינו אותו "שעון העיר".',
    quote: '"פעל רק לפי אותו כלל שתוכל לרצות שיהפוך לחוק אוניברסלי."',
  },
  {
    id: 'mill',
    name: 'ג\'ון סטיוארט מיל',
    era: '1806–1873',
    image: './images/mill.webp',
    emoji: '🌻',
    bio: 'פילוסוף בריטי ומייסד האוטיליטריזם המודרני. ילד פלא שקרא יוונית בגיל שלוש - וסבל מדיכאון קשה בגיל 20. פיתח את עקרון האושר המרבי: מוסרי הוא מה שמקדם את הרווחה הכוללת.',
    quote: '"עדיף להיות סוקרטס לא מרוצה מאשר שוטה מרוצה."',
  },
  {
    id: 'nietzsche',
    name: 'פרידריך ניטשה',
    era: '1844–1900',
    image: './images/nietzsche.webp',
    emoji: '⚡',
    bio: 'פילוסוף גרמני, מבקר המוסר הנוקב ביותר בתולדות הפילוסופיה. לא שאל "מה מוסרי?" אלא "מאיפה בא המוסר?" - וגילה שמאחורי ערכים "נעלים" לעיתים מסתתרים כוח, טינה, ורצון לשלוט. מת לאחר שנות מחלה קשות, אחרי שאחותו ניכסה כתביו לצרכים לאומניים שהיה שונא.',
    quote: '"אין עובדות מוסריות. יש רק פרשנות מוסרית של עובדות."',
  },
  {
    id: 'hume',
    name: 'דייוויד יום',
    era: '–1776',
    image: './images/hume.webp',
    emoji: '🌊',
    bio: 'פילוסוף סקוטי ואחד האמפיריציסטים הרדיקליים ביותר. טען שכל הידע מקורו בתפיסה החושית - ושהשכל לבדו אינו מסוגל להיות מקור לידיעה על העולם. הביקורת שלו על הסיבתיות ועל האינדוקציה לא זכתה למענה מלא עד היום.',
    quote: '"הרגל הוא המנחה הגדול של החיים האנושיים."',
  },
  {
    id: 'gettier',
    name: 'אדמונד גטייה',
    era: '1927–2021',
    image: './images/gettier.webp',
    emoji: '⚙️',
    bio: 'פילוסוף אמריקאי שכתב שלושה עמודים בשנת 1963 - ושינה 2500 שנות פילוסופיה. המאמר "האם אמונה אמיתית מוצדקת היא ידע?" שבר את הנוסחה של אפלטון. גטייה עצמו כמעט לא פרסם דבר לאחר מכן.',
    quote: '"אמונה אמיתית מוצדקת - ועדיין לא ידע."',
  },
  {
    id: 'popper',
    name: 'קרל פופר',
    era: '1902–1994',
    image: './images/popper.webp',
    emoji: '🔬',
    bio: 'פילוסוף אוסטרי-בריטי שהציע את הקריטריון המדעי של הפרכה. לפי פופר, לא מה שמאמת תיאוריה הופך אותה למדעית - אלא מה שיכול להפריך אותה. ביקורתו על פסיכואנליזה ומרקסיזם כ"לא מדעיים" עוררה ויכוח חריף.',
    quote: '"המדע לא מתקדם על ידי אימות - אלא על ידי הפרכה."',
  },
  {
    id: 'spinoza',
    name: 'ברוך שפינוזה',
    era: '1632–1677',
    image: './images/spinoza.webp',
    emoji: '✡️',
    bio: 'פילוסוף הולנדי-יהודי שהוחרם מקהילתו בגיל 23 בשל רעיונותיו המהפכניים. פיתח את המונאיזם - הרעיון שאלוהים והטבע הם ישות אחת (Deus sive Natura). "האתיקה" שלו, שנכתבה כמערכת גיאומטרית, היא אחד הטקסטים הפילוסופיים המרשימים ביותר שנכתבו.',
    quote: '"האדם החופשי לא חושב על דבר פחות מאשר על המוות, וחכמתו היא עיון לא על המוות אלא על החיים."',
  },
  {
    id: 'berkeley',
    name: 'ג\'ורג\' ברקלי',
    era: '1685–1753',
    image: './images/berkeley.webp',
    emoji: '👁️',
    bio: 'פילוסוף אירי וביסקופ אנגליקני שטען כי לחומר אין קיום עצמאי. פיתח את האידיאליזם הסובייקטיבי - esse est percipi ("להיות זה להיתפס"). על אף שנראה קיצוני, תורתו נועדה להגן על הדת מפני המטריאליזם.',
    quote: '"קיומו של דבר שנתפס על ידי החושים אינו דבר שונה מהיתפסותו."',
  },
  {
    id: 'bostrom',
    name: 'ניק בוסטרום',
    era: '1973–',
    image: './images/bostrom.webp',
    emoji: '🖥️',
    bio: 'פילוסוף שוודי, מייסד מכון עתיד האנושות באוקספורד. ידוע בטיעון הסימולציה (2003) - ייתכן שאנו חיים בתוך סימולציה ממוחשבת - ובעבודתו על סיכוני הקיום של האנושות.',
    quote: '"אם ציביליזציות פוסט-אנושיות מריצות מספר רב של סימולציות, אזי מרבית המוחות בעלי חוויות כשלנו חיים בתוך סימולציה."'
  },
  {
    id: 'thomson',
    name: 'ג\'ודית ג\'רביס תומסון',
    era: '1929–2020',
    image: './images/thomson.webp',
    emoji: '🦉',
    bio: 'פילוסופית אמריקאית מהמובילות בתחום האתיקה. ידועה בניסוי המחשבתי "בעיית הקרונית" שפרסמה ב-1967 - אחד הכלים הפדגוגיים הנפוצים ביותר בפילוסופיה המוסרית.',
    quote: '"העובדה שאתה עלול לגרום נזק לאחד אינה הופכת אותך למי שאסור לו לסייע לחמישה."'
  },
  // Psychology thinkers
  {
    id: 'wundt',
    name: 'וילהלם וונדט',
    era: '1832–1920',
    emoji: '🧪',
    image: './images/wundt.webp',
    subject: 'psychology',
    bio: 'הפסיכולוג הגרמני שהקים ב-1879 את המעבדה הפסיכולוגית הראשונה בעולם, בלייפציג. הכריז שהנפש היא מושא לחקירה מדעית - ולא לספקולציה פילוסופית. השיטה שלו נזנחה; הרעיון שלו כובש עד היום.',
    quote: '"הספר שאני מגיש כאן לציבור הוא ניסיון להתוות תחום חדש של מדע."',
  },
  {
    id: 'james',
    name: 'ויליאם ג\'יימס',
    era: '1842–1910',
    emoji: '🌊',
    image: './images/james.webp',
    subject: 'psychology',
    bio: 'פילוסוף-פסיכולוג אמריקאי מהרווארד. טען כנגד וונדט שהתודעה איננה שרשרת של רגעים בדידים - היא נהר. הגה את המושג "זרם התודעה" וייסד את הפסיכולוגיה הפונקציונלית: לא ממה עשויה התודעה, אלא מה היא עושה.',
    quote: '"התודעה אינה מצטיירת לעצמה כקטועה לחתיכות. אין בה דבר שאפשר לחבר - היא זורמת."',
  },
  {
    id: 'freud',
    name: 'זיגמונד פרויד',
    era: '1856–1939',
    emoji: '🛋',
    image: './images/freud.webp',
    subject: 'psychology',
    bio: 'רופא אוסטרי מווינה שהמציא את הפסיכואנליזה בסוף המאה ה-19. גילה שרוב הפעילות הנפשית מתרחשת מתחת לפני השטח, בלא-מודע, ומשפיעה על כל התנהגות מודעת. הפך את התפיסה המערבית של עצמנו על פיה.',
    quote: '"החלוקה של הנפשי לחלק מודע ולחלק לא-מודע היא הנחת היסוד של הפסיכואנליזה."',
  },
  {
    id: 'jung',
    name: 'קרל גוסטב יונג',
    era: '1875–1961',
    emoji: '🌀',
    image: './images/jung.webp',
    subject: 'psychology',
    bio: 'פסיכולוג שוויצרי, תלמידו הבכיר של פרויד ולימים יריבו. טען שמתחת ללא-מודע האישי קיים לא-מודע קולקטיבי - שכבה משותפת לכל בני האדם, המכילה ארכיטיפים שחוזרים במיתוסים, חלומות וסיפורים בכל התרבויות.',
    quote: '"בנוסף לתודעה הישירה שלנו, קיימת מערכת נפשית שנייה בעלת אופי קולקטיבי, אוניברסלי ובלתי-אישי, שהיא זהה בכל היחידים."',
  },
  {
    id: 'skinner',
    name: 'ב.פ. סקינר',
    era: '1904–1990',
    emoji: '🐦',
    image: './images/skinner.webp',
    subject: 'psychology',
    bio: 'פסיכולוג אמריקאי מהרווארד שהוביל את מהפכת הביהביוריזם הרדיקלי. טען שכל הדיבור על "נפש" פנימית הוא ספקולציה חסרת-תוחלת - הפסיכולוגיה יכולה להיות מדע רק אם תמדוד התנהגות נצפית ואת תוצאותיה: חיזוקים ועונשים.',
    quote: '"אדם אינו פועל על העולם, העולם פועל עליו."',
  },
  {
    id: 'rogers',
    name: 'קרל רוג\'רס',
    era: '1902–1987',
    emoji: '🌱',
    image: './images/rogers.webp',
    subject: 'psychology',
    bio: 'פסיכולוג אמריקאי, מייסד הפסיכולוגיה ההומניסטית. דחה גם את פרויד (שראה באדם קורבן של דחפים מודחקים) וגם את סקינר (שראה בו מכונה ביולוגית) - וטען שהאדם הוא סובייקט של חייו, שיש בו נטייה פנימית לצמוח כשמספקים לו את התנאים המתאימים.',
    quote: '"מוטב לתפוס זאת כנטייה לקראת הגשמה, לקראת מימוש עצמי, הכוללת לא רק את שימורו של האורגניזם אלא גם את פיתוחו."',
  },
  // Psychology chapter 2 — "What drives us?"
  {
    id: 'adler',
    name: 'אלפרד אדלר',
    era: '1870–1937',
    emoji: '⬆️',
    image: './images/adler.webp',
    subject: 'psychology',
    bio: 'פסיכולוג אוסטרי, מקורב לפרויד ולימים יריבו. עמד בראש האגודה הפסיכואנליטית של וינה עד פרישתו הסוערת ב-1911. טען שהמנוע הנסתר של האדם אינו מיני אלא הרצון להפסיק להרגיש קטן - הוא כינה זאת "שאיפה לעליונות".',
    quote: '"להיות אדם פירושו לחוש נחיתות שדוחפת ללא הרף אל ההתגברות עליה."',
  },
  {
    id: 'maslow',
    name: 'אברהם מאסלו',
    era: '1908–1970',
    emoji: '🔺',
    image: './images/maslow.webp',
    subject: 'psychology',
    bio: 'פסיכולוג אמריקאי שביקש להסביר מדוע אותו אדם רוצה דברים שונים בשלבים שונים בחייו. סידר את הצרכים האנושיים לפירמידה עולה, ממה שנחוץ לחיים ועד למימוש עצמי, וטען שצורך שמסופק מפסיק להניע.',
    quote: '"מה שאדם יכול להיות, עליו להיות."',
  },
  {
    id: 'frankl',
    name: 'ויקטור פרנקל',
    era: '1905–1997',
    emoji: '✡️',
    image: './images/frankl.webp',
    subject: 'psychology',
    bio: 'פסיכיאטר וינאי שניצל ממחנות ההשמדה של הנאצים. פיתח את הלוגותרפיה, "האסכולה הווינאית השלישית", וטען שהמניע העמוק ביותר של האדם אינו סיפוק דחפים או שאיפה לכוח - אלא חיפוש אחר משמעות.',
    quote: '"הכל אפשר ליטול מאדם חוץ מדבר אחד: החירות האחרונה, לבחור את עמדתו בכל נסיבות שהן."',
  },
  {
    id: 'fromm',
    name: 'אריך פרום',
    era: '1900–1980',
    emoji: '🕊️',
    image: './images/fromm.webp',
    subject: 'psychology',
    bio: 'פסיכואנליטיקאי גרמני-יהודי שברח מגרמניה הנאצית לארה"ב. הפך את השאלה על ראשה: אם החירות היקרה כל כך, למה אנשים מוסרים אותה מרצון? הראה שהחופש עשוי להיות מכביד, ושהאדם המודרני קונה הקלה במחיר של אוטונומיה.',
    quote: '"החירות, אף שהביאה לו עצמאות ותבונה, הפכה אותו למבודד, ובשל כך לחרד וחסר אונים."',
  },
  {
    id: 'deci',
    name: 'אדוארד דצ\'י',
    era: '1942–',
    emoji: '🎯',
    image: './images/deci.webp',
    subject: 'psychology',
    bio: 'פסיכולוג אמריקאי שחקר מוטיבציה במעבדה. גילה עם ראיאן שתגמול חיצוני על משימה שאוהבים דווקא מזיז את הסיבה לפעולה מבפנים החוצה, ובהמשך זיהה שלושה צרכים בסיסיים: אוטונומיה, מסוגלות ושייכות.',
    quote: '"במקום לשאול איך אני יכול להניע אנשים, עלינו לשאול כיצד ליצור את התנאים שבהם אנשים יניעו את עצמם."',
  },
  // Psychology chapter 3 — "Where does who I am come from?"
  {
    id: 'bowlby',
    name: 'ג\'ון בולבי',
    era: '1907–1990',
    emoji: '🔗',
    image: './images/bowlby.webp',
    subject: 'psychology',
    bio: 'פסיכיאטר ופסיכואנליטיקאי בריטי, מייסד תיאוריית ההתקשרות. עבד עם ילדים שגדלו במוסדות אחרי מלחמת העולם השנייה, וגילה שקשר יציב עם דמות מטפלת בשנתיים הראשונות מעצב את דפוס היחסים לאורך כל החיים. הפך את "הצורך באמא" מפינוק לביולוגיה.',
    quote: '"קשרים אינטימיים לבני אדם אחרים הם הציר שסביבו סובבים חייו של אדם, לא רק בינקות ובילדות, אלא לאורך שנות הבגרות ועד זקנה."',
  },
  {
    id: 'winnicott',
    name: 'דונלד ויניקוט',
    era: '1896–1971',
    emoji: '🧸',
    image: './images/winnicott.webp',
    subject: 'psychology',
    bio: 'רופא ילדים ופסיכואנליטיקאי בריטי. הציע את המושג "אם טובה דיה", שנחוצה לילד לא מתוך שלמות אלא מתוך כישלון מדוד בזמן הנכון. הכישלון הקטן הוא מה שמאפשר לילד לפתח את היכולת להתמודד לבד.',
    quote: '"האם הטובה דיה מתחילה בהתאמה כמעט מלאה לצורכי תינוקה, וככל שהזמן עובר היא מתאימה עצמה פחות ופחות, בהדרגה, בהתאם ליכולתו הגדלה של התינוק להתמודד עם כישלונה."',
  },
  {
    id: 'erikson',
    name: 'אריק אריקסון',
    era: '1902–1994',
    emoji: '🪜',
    image: './images/erikson.webp',
    subject: 'psychology',
    bio: 'פסיכולוג התפתחותי גרמני-אמריקאי. הרחיב את פרויד בכיוון אחד מכריע: העיצוב הנפשי אינו נגמר בילדות. הציע שמונה שלבי חיים, מלידה עד זקנה, שבכל אחד יש משבר לפתור. מי שלא פותר משבר, נושא אותו הלאה.',
    quote: '"ילדים בריאים לא יפחדו מהחיים, אם למבוגרים שסביבם יש די שלמות כדי לא לפחד מהמוות."',
  },
  {
    id: 'kohut',
    name: 'היינץ קוהוט',
    era: '1913–1981',
    emoji: '👁️',
    image: './images/kohut.webp',
    subject: 'psychology',
    bio: 'פסיכואנליטיקאי אמריקאי יליד וינה, מייסד פסיכולוגיית העצמי. טען שהעצמי אינו נבנה מתוך אימות פנימי, אלא מתוך היראות בעיני אדם אחר. "הניצוץ בעין ההורה" הוא התנאי הבסיסי להתפתחות תחושת ערך.',
    quote: '"הניצוץ בעיניה של האם, המשקף את תצוגתו של הילד."',
  },
  {
    id: 'bandura',
    name: 'אלברט בנדורה',
    era: '1925–2021',
    emoji: '🎭',
    image: './images/bandura.webp',
    subject: 'psychology',
    bio: 'פסיכולוג קנדי-אמריקאי מסטנפורד. הראה שאדם לומד לא רק מהתנאה, אלא בעיקר מהתבוננות באחרים. ניסוי הבובה "בובו" ב-1961 הוכיח שילדים מחקים אלימות שראו אצל מבוגר. הציע את הדגם השלישי אחרי פרויד וסקינר: לא דחפים, לא חיזוקים, אלא למידה חברתית.',
    quote: '"הלמידה הייתה מפרכת, שלא לומר מסוכנת, לו היו בני אדם נאלצים להסתמך רק על תוצאות מעשיהם שלהם. למרבה המזל, רוב ההתנהגות האנושית נלמדת בהתבוננות, דרך מודלים."',
  },
  // Psychology chapter 4 — "Why are we locked into patterns?"
  {
    id: 'klein',
    name: 'מלאני קליין',
    era: '1882–1960',
    emoji: '🪆',
    image: './images/klein.webp',
    subject: 'psychology',
    bio: 'פסיכואנליטיקאית ילידת וינה שפעלה בלונדון. חלוצת הפסיכואנליזה של ילדים דרך משחק. פיתחה את תיאוריית יחסי אובייקט: אנחנו סופגים לתוכנו דמויות של האנשים החשובים בחיינו, והן ממשיכות לפעול בפנים גם עשרות שנים אחרי.',
    quote: '"תודה קשורה קשר הדוק לאמון בדמויות טובות. דרך תהליכי ההשלכה וההפנמה, דרך עושר פנימי שניתן החוצה ומופנם בחזרה, מתרחשים העשרה והעמקה של האני."',
  },
  {
    id: 'anna-freud',
    name: 'אנה פרויד',
    era: '1895–1982',
    emoji: '🛡️',
    image: './images/anna-freud.webp',
    subject: 'psychology',
    bio: 'פסיכואנליטיקאית ילידת וינה, בתו הצעירה של זיגמונד פרויד ופסיכואנליטיקאית בזכות עצמה. הפנתה את הזרקור מהדחפים אל האני, ומיפתה מערכת שלמה של מנגנוני הגנה, אסטרטגיות אוטומטיות שהנפש מפעילה כדי להרחיק חרדה.',
    quote: '"ספר זה עוסק בבעיה אחת: הדרכים והאמצעים שבהם האני מרחיק מעליו אי-נעימות וחרדה, ומפעיל שליטה על התנהגות אימפולסיבית, על רגשות ועל דחפים."',
  },
  {
    id: 'beck',
    name: 'אהרון בק',
    era: '1921–2021',
    emoji: '💭',
    image: './images/beck.webp',
    subject: 'psychology',
    bio: 'פסיכיאטר אמריקאי שהוכשר כפסיכואנליטיקאי וגילה בקליניקה תופעה חדשה: בין האירוע לרגש עוברת מחשבה מהירה, כמעט בלתי מורגשת. פיתח את הטיפול הקוגניטיבי (CBT), שהפך לטיפול הנחקר ביותר בעולם על דיכאון וחרדה, והציב את הפסיכותרפיה על בסיס אמפירי.',
    quote: '"הטיפול הקוגניטיבי מבקש להקל על מצוקות נפשיות באמצעות תיקון תפיסות שגויות ואותות פנימיים. תיקון אמונות שגויות מפחית תגובות מוגזמות."',
  },
  {
    id: 'van-der-kolk',
    name: 'בסל ון דר קולק',
    era: '1943–',
    emoji: '🫀',
    image: './images/van-der-kolk.webp',
    subject: 'psychology',
    bio: 'פסיכיאטר וחוקר טראומה הולנדי-אמריקאי. הראה שטראומה אינה רק זיכרון של אירוע, אלא חותם שהיא מותירה על הגוף ועל מערכת האזעקה שלו. ספרו "נרשם בגוף" הפך לרב-מכר עצום, ובד בבד גם שנוי במחלוקת בקהילה המדעית.',
    quote: '"טראומה אינה רק אירוע שהתרחש בעבר. היא גם החותם שהותירה החוויה על הנפש, על המוח ועל הגוף. לחותם הזה יש השלכות מתמשכות על האופן שבו האורגניזם מצליח לשרוד בהווה."',
  },
  // Economics thinkers
  {
    id: 'mill-econ',
    name: 'ג\'ון סטיוארט מיל',
    era: '1806–1873',
    emoji: '🌻',
    image: './images/mill1.webp',
    subject: 'economics',
    bio: 'פילוסוף וכלכלן בריטי. הבחין בין חוקי הייצור (טבעיים) לחוקי החלוקה (חברתיים) - הבחנה ששינתה את ההיסטוריה של החשיבה הכלכלית.',
    quote: '"השאלה לעתיד היא לא איך לייצר יותר - אלא איך לחלק טוב יותר."',
  },
  {
    id: 'smith',
    name: 'אדם סמית',
    era: '1723–1790',
    emoji: '🏭',
    image: './images/smith.webp',
    subject: 'economics',
    bio: 'הכלכלן הסקוטי שהניח את היסודות לכלכלה המודרנית. ידוע במטאפורת "היד הנעלמה" - שוק חופשי המתואם את עצמו ללא תכנון מרכזי.',
    quote: '"אין זה מנדיבותו של הקצב, של מבשל השכר, או של האופה, שאנו מצפים לארוחת הערב שלנו, אלא מהתחשבותם באינטרסים שלהם."',
  },
  {
    id: 'locke',
    name: 'ג\'ון לוק',
    era: '1632–1704',
    emoji: '📜',
    image: './images/locke.webp',
    subject: 'economics',
    bio: 'הפילוסוף האנגלי שניסח את הבסיס הפילוסופי לזכות הקניין הפרטי - לא כהסכם חברתי אלא כזכות טבעית הנובעת מבעלות האדם על עצמו.',
    quote: '"לכל אדם יש קניין באישיותו עצמה... עמל גופו ועבודת ידיו הם, כפי שניתן לומר, שלו במלואם."',
  },
  {
    id: 'samuelson',
    name: 'פול סמואלסון',
    era: '1915–2009',
    emoji: '📊',
    image: './images/samuelson.webp',
    subject: 'economics',
    bio: 'הכלכלן האמריקאי הראשון לזכות בפרס נובל לכלכלה (1970). ספרו "כלכלה" (1948) הגדיר את הדיסציפלינה למשך עשורים.',
    quote: '"כלכלה היא חקר האופן שבו אנשים ואומות בוחרים להעסיק משאבים יצרניים נדירים..."',
  },
  {
    id: 'marx',
    name: 'קרל מרקס',
    era: '1818–1883',
    emoji: '⚙️',
    image: './images/marx.webp',
    subject: 'economics',
    bio: 'הפילוסוף והכלכלן הגרמני שביקר את הקפיטליזם מהיסוד. ב"הקפיטל" פיתח את תורת ערך העבודה וניתח את מנגנוני הניצול המובנים בייצור הקפיטליסטי.',
    quote: '"ההיסטוריה של כל החברה שהתקיימה עד כה היא היסטוריה של מאבקי מעמדות."',
  },
  {
    id: 'walras',
    name: 'לאון וולראס',
    era: '1834–1910',
    emoji: '🔢',
    image: './images/walras.webp',
    subject: 'economics',
    bio: 'הכלכלן השוויצרי שייסד את הכלכלה הנאו-קלאסית. פיתח את תורת שיווי המשקל הכללי - הרעיון שניתן לתאר מתמטית כיצד כל השווקים בכלכלה מגיעים לאיזון בו-זמנית.',
    quote: '"המחירים הם פתרון של מערכת משוואות סימולטנית."',
  },
  {
    id: 'sandel',
    name: 'מייקל סנדל',
    era: '1953–',
    emoji: '🏛️',
    image: './images/sandel.webp',
    subject: 'economics',
    bio: 'פילוסוף פוליטי אמריקאי מהרווארד. ידוע בביקורתו על הקפיטליזם וטיעונו שיש ספירות של חיים - חינוך, בריאות, דמוקרטיה - שבהן כסף לא אמור לקבוע.',
    quote: '"השוק אינו כלי ניטרלי - הוא מחדיר ערכים מסוימים לתחומים שבהם ערכים אחרים חשובים יותר."',
  },
  {
    id: 'keynes',
    name: 'ג\'ון מיינרד קיינס',
    era: '1883–1946',
    emoji: '💰',
    image: './images/keynes.webp',
    subject: 'economics',
    bio: 'הכלכלן הבריטי שטען שהשוק לא תמיד מתקן את עצמו ושמדינות חייבות להוציא כסף במשברים.',
    quote: '"בטווח הארוך, כולנו מתים."',
  },
  {
    id: 'friedman',
    name: 'מילטון פרידמן',
    era: '1912–2006',
    emoji: '🗽',
    image: './images/friedman.webp',
    subject: 'economics',
    bio: 'הכלכלן האמריקאי מאוניברסיטת שיקגו שטען שהשוק החופשי הוא יסוד החירות האנושית.',
    quote: '"אין ארוחת חינם."',
  },
  {
    id: 'sen',
    name: 'אמרטיה סן',
    era: '1933–',
    emoji: '🌍',
    image: './images/sen.webp',
    subject: 'economics',
    bio: 'הכלכלן ההודי, חתן פרס נובל, שטען שפיתוח אמיתי אינו גידול ב-GDP אלא הרחבת היכולות של אנשים.',
    quote: '"פיתוח הוא חירות."',
  },
  {
    id: 'jevons',
    name: 'ויליאם סטנלי ג\'בונס',
    era: '1835–1882',
    emoji: '💎',
    image: './images/jevons.webp',
    subject: 'economics',
    bio: 'הכלכלן האנגלי שגילה את "התועלת השולית" - שערך מגיע לא מעבודה, אלא מהרצון של היחידה הבאה.',
    quote: '"ערך הוא יחס סובייקטיבי שאדם מקנה לדבר."',
  },
  {
    id: 'marshall',
    name: 'אלפרד מרשל',
    era: '1842–1924',
    emoji: '✂️',
    image: './images/marshall.webp',
    subject: 'economics',
    bio: 'הכלכלן הבריטי שאיחד את ההיצע והביקוש לדיאגרמה אחת - והניח את היסוד לכלכלה המודרנית.',
    quote: '"אנחנו יכולים להתווכח אם זה הסכין העליון או התחתון של המספריים שחותך פיסת נייר. אבל ברור שיש צורך בשני הסכינים."',
  },
  {
    id: 'kahneman',
    name: 'דניאל קהנמן',
    era: '1934–2024',
    emoji: '🧠',
    // Per-subject portraits: `image` is the fallback (used when the
    // rendering context's subject has no entry in `images[]`). Every
    // Kahneman-facing surface knows its subject and resolves via
    // _thinkerImage(t, subject) — see index.html and
    // generate-share-cards.mjs. Files deliberately suffixed so no
    // filename carries implicit-subject meaning.
    image: './images/kahneman-econ.webp',
    images: {
      economics:  './images/kahneman-econ.webp',
      psychology: './images/kahneman-psy.webp',
    },
    subject: 'economics',
    // Kahneman was a psychologist by training whose Nobel was in economics.
    // Primary bucket is economics (his Nobel context, frame color); the
    // subjects[] array lets dialogues in either bucket reference him without
    // tripping the validator's single-subject mismatch check.
    subjects: ['economics', 'psychology'],
    bio: 'הפסיכולוג הישראלי-אמריקאי שזכה בפרס נובל לכלכלה ב-2002 על הצגת ההטיות הקוגניטיביות שמשפיעות על החלטות כלכליות.',
    quote: '"הפסד של 100 דולר מורגש בערך פי שניים יותר מרווח של 100 דולר."',
  },
  {
    id: 'ricardo',
    name: 'דייוויד ריקרדו',
    era: '1772–1823',
    emoji: '🌾',
    image: './images/ricardo.webp',
    subject: 'economics',
    bio: 'הכלכלן הבריטי שניסח את חוק התפוקה השולית הפוחתת ואת תאוריית חלוקת ההכנסות בין מעמדות.',
    quote: '"כשמוסיפים יותר ויותר עבודה לאותה כמות של אדמה - היחידה הנוספת של עבודה תוסיף פחות תפוקה מהקודמת."',
  },
  {
    id: 'piketty',
    name: 'תומאס פיקטי',
    era: '1971–',
    emoji: '📊',
    image: './images/piketty.webp',
    subject: 'economics',
    bio: 'הכלכלן הצרפתי שמדד את ההון על פני 300 שנה, וגילה את הנוסחה r > g - תשואת ההון גדולה תמיד מקצב הצמיחה.',
    quote: '״כאשר תשואת ההון חורגת באופן מתמשך משיעור הצמיחה של הכלכלה - עושר תורשתי גדל מהר יותר מהכלכלה כולה.״',
  },
  {
    id: 'aquinas',
    name: 'תומאס אקווינס',
    era: '1225–1274',
    emoji: '✝️',
    image: './images/aquinas.webp',
    subject: 'economics',
    bio: 'נזיר דומיניקני ופילוסוף מימי הביניים שניסח את הרעיון של "המחיר הצודק", וקבע שלא כל מה שחוקי בשוק הוא צודק.',
    quote: '״למכור דבר ביותר מערכו האמיתי הוא חטא, אפילו אם אין חוק שאוסר זאת.״',
  },
  {
    id: 'pareto',
    name: 'וילפרדו פארטו',
    era: '1848–1923',
    emoji: '⚖️',
    image: './images/pareto.webp',
    subject: 'economics',
    bio: 'הכלכלן האיטלקי שניסה להפריד את הכלכלה משאלות מוסר, וניסח את מושג "יעילות פארטו" שהפך לבסיס הכלכלה המודרנית.',
    quote: '״מצב כלכלי הוא אופטימלי כאשר אי אפשר לשפר את רווחתו של אדם אחד בלי להפחית את רווחתו של אדם אחר.״',
  },
  {
    id: 'rawls',
    name: 'ג\'ון רולס',
    era: '1921–2002',
    emoji: '⚖️',
    image: './images/rawls.webp',
    subject: 'economics',
    bio: 'הפילוסוף האמריקאי שניסח את "מסך הבערות", ניסוי מחשבתי שמנסה להגדיר חברה צודקת מבלי לדעת מה יהיה מיקומך בה.',
    quote: '״רק מאחורי מסך של בערות, נוכל לבחור עקרונות צדק אמיתיים.״',
  },
  {
    id: 'nozick',
    name: 'רוברט נוזיק',
    era: '1938–2002',
    emoji: '🗽',
    image: './images/nozick.webp',
    subject: 'economics',
    bio: 'הפילוסוף האמריקאי הליברטריאני שניסח את "צדק כזכאות" כתגובה לרולס: צדק נמדד בתהליך, לא בתוצאה.',
    quote: '״מצב צודק הוא כל מצב שהושג בדרכים צודקות.״',
  },
  {
    id: 'hayek',
    name: 'פרידריך הייק',
    era: '1899–1992',
    emoji: '🌬️',
    image: './images/hayek.webp',
    subject: 'economics',
    bio: 'הכלכלן האוסטרי-בריטי שטען שהמושג "צדק חברתי" חסר משמעות: לא ניתן לכנות תוצאה של תהליך ספונטני "צודקת" או "לא צודקת".',
    quote: '״צדק יכול להיות תכונה של התנהגות אנושית, אך לא של מצב שאיש לא יצר במכוון.״',
  },
];

const THINKERS_EN = [
  { id:'socrates', name:'Socrates', era:'470–399 BCE', emoji:'🦉', image:'./images/socrates.webp', bio:'The great Athenian philosopher who wrote nothing yet transformed all of Western thought. Famous for the Socratic method of dialogue and the paradox that true wisdom begins with knowing you know nothing.', quote:'"I know that I know nothing."' },
  { id:'plato', name:'Plato', image:'./images/plato.webp', era:'428–348 BCE', emoji:'🏛', bio:'Student of Socrates and master of allegory. Developed the Theory of Forms - the world we perceive is only a shadow of true reality. Founded the Academy, the first institution of higher learning in the Western world.', quote:'"Philosophical inquiry is the liberation of the soul."' },
  { id:'russell', name:'Bertrand Russell', image:'./images/russell.webp', era:'1872–1970', emoji:'📐', bio:'British philosopher, mathematician, and Nobel laureate. Saw philosophy as a critical tool for examining life and the world - and for learning to live with uncertainty rather than false certainty.', quote:'"The philosopher is one who can live with uncertainty."' },
  { id:'wittgenstein', name:'Wittgenstein', image:'./images/wittgenstein.webp', era:'1889–1951', emoji:'🔤', bio:'One of the most influential philosophers of the 20th century. Claimed the limits of our language are the limits of our world - and that most philosophical problems dissolve once we clarify what we are actually saying.', quote:'"The limits of my language mean the limits of my world."' },
  { id:'aurelius', name:'Marcus Aurelius', image:'./images/aurelius.webp', era:'121–180 CE', emoji:'👑', bio:'Roman emperor and Stoic philosopher. Wrote the Meditations - a private journal of daily reminders - as self-discipline for living well. One of history\'s most powerful men who genuinely tried to live by his philosophy.', quote:'"The happiness of your life depends upon the quality of your thoughts."' },
  { id:'aristotle', name:'Aristotle', image:'./images/aristotle.webp', era:'384–322 BCE', emoji:'🌿', bio:'Student of Plato who ultimately broke with his teacher. Created formal logic, empirical biology, and political philosophy. Defined happiness as eudaimonia - flourishing through reason and virtue.', quote:'"Wonder is the beginning of philosophy."' },
  { id:'descartes', name:'Descartes', era:'1596–1650', image:'./images/descartes.webp', emoji:'🕯️', bio:'Father of modern philosophy. Sought a foundation for knowledge that could withstand radical doubt - and found it in the thinking self: "I think, therefore I am."', quote:'"I think, therefore I am."' },
  { id:'kant', name:'Immanuel Kant', era:'1724–1804', image:'./images/kant.webp', emoji:'⚖️', bio:'German philosopher considered one of the greatest of all time. Created the categorical imperative - a universal moral principle grounded in reason, not consequences. Famously lived by an unvarying daily schedule in Königsberg.', quote:'"Act only according to that maxim whereby you can will it to become a universal law."' },
  { id:'mill', name:'John Stuart Mill', era:'1806–1873', image:'./images/mill.webp', emoji:'🌻', bio:'British philosopher and founder of modern utilitarianism. A child prodigy who read Greek at three, and suffered a severe breakdown at 20. Developed the greatest happiness principle and championed individual liberty.', quote:'"It is better to be Socrates dissatisfied than a fool satisfied."' },
  { id:'nietzsche', name:'Friedrich Nietzsche', era:'1844–1900', image:'./images/nietzsche.webp', emoji:'⚡', bio:'German philosopher and the most incisive critic of morality in philosophical history. Did not ask "what is moral?" but "where does morality come from?" - and found resentment lurking behind many noble-sounding values.', quote:'"There are no moral facts. There is only moral interpretation of facts."' },
  { id:'hume', name:'David Hume', era:'1711–1776', image:'./images/hume.webp', emoji:'🌊', bio:'Scottish philosopher and one of the most radical empiricists. Argued that all knowledge flows from experience and that reason alone can prove nothing about the world. His problem of induction remains philosophically unsolved.', quote:'"Custom is the great guide of human life."' },
  { id:'gettier', name:'Edmund Gettier', era:'1927–2021', image:'./images/gettier.webp', emoji:'⚙️', bio:'American philosopher who upended 2500 years of epistemology with a three-page paper in 1963. His counterexamples to the justified-true-belief analysis of knowledge sparked a debate that has never fully closed.', quote:'"Justified true belief - and still not knowledge."' },
  { id:'popper', name:'Karl Popper', era:'1902–1994', image:'./images/popper.webp', emoji:'🔬', bio:'Austrian-British philosopher who proposed the falsifiability criterion for science. A theory is scientific not because it is confirmed but because it can be refuted. His critique of Freud and Marx as unscientific remains provocative.', quote:'"Science does not progress through verification - but through falsification."' },
  { id:'spinoza', name:'Baruch Spinoza', era:'1632–1677', image:'./images/spinoza.webp', emoji:'✡️', bio:'Dutch-Jewish philosopher excommunicated from his community at age 23 for his revolutionary ideas. Developed monism - the idea that God and Nature are one substance (Deus sive Natura). His Ethics, written as a geometric system, is one of the most architecturally impressive texts in all of philosophy.', quote:'"The free man thinks of nothing less than of death, and his wisdom is a meditation not on death but on life."' },
  { id:'berkeley', name:'George Berkeley', era:'1685–1753', image:'./images/berkeley.webp', emoji:'👁️', bio:'Irish philosopher and Anglican bishop who argued that matter has no independent existence. Developed subjective idealism - esse est percipi ("to be is to be perceived"). Though it seems extreme, his theory was designed to defend religion against materialism, and received unexpected support from quantum physics.', quote:'"The existence of a thing perceived by the senses is nothing different from its being perceived."' },
  { id:'thomson', name:'Judith Jarvis Thomson', era:'1929–2020', image:'./images/thomson.webp', emoji:'🦉', bio:'American moral philosopher best known for the Trolley Problem thought experiment (1967), one of the most widely used tools in ethics. Her work on rights and personal identity reshaped analytic philosophy.', quote:'"The fact that you may cause harm to one does not make it impermissible for you to save five."' },
  { id:'bostrom', name:'Nick Bostrom', era:'1973–', image:'./images/bostrom.webp', emoji:'🖥️', bio:'Swedish philosopher and founding director of the Future of Humanity Institute at Oxford. Best known for the simulation argument (2003) and his work on existential risks to humanity.', quote:'"If posthuman civilizations run a large number of simulations of their forebears, then the vast majority of all minds having experiences like ours live inside a simulation."' },
  // Economics thinkers
  { id:'mill-econ', name:'John Stuart Mill', era:'1806–1873', image:'./images/mill1.webp', emoji:'🌻', subject:'economics', bio:'British philosopher and economist. Distinguished between the laws of production (natural) and the laws of distribution (social) - a distinction that changed the history of economic thought.', quote:'"The question for the future is not how to produce more - but how to distribute better."' },
  { id:'smith', name:'Adam Smith', era:'1723–1790', emoji:'🏭', image:'./images/smith.webp', subject:'economics', bio:'The Scottish economist who laid the foundations of modern economics. Famous for the "invisible hand" metaphor - a self-coordinating free market without central planning.', quote:'"It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest."' },
  { id:'locke', name:'John Locke', era:'1632–1704', emoji:'📜', image:'./images/locke.webp', subject:'economics', bio:'The English philosopher who formulated the philosophical basis for private property - not as a social agreement but as a natural right derived from a person\'s ownership of themselves.', quote:'"Every man has a property in his own person… the labour of his body, and the work of his hands, we may say, are properly his."' },
  { id:'samuelson', name:'Paul Samuelson', era:'1915–2009', emoji:'📊', image:'./images/samuelson.webp', subject:'economics', bio:'The first American economist to win the Nobel Prize in Economics (1970). His textbook "Economics" (1948) defined the discipline for decades.', quote:'"Economics is the study of how people and nations choose to employ scarce productive resources - labor, capital, land - to produce commodities and distribute them for consumption."' },
  { id:'marx', name:'Karl Marx', era:'1818–1883', emoji:'⚙️', image:'./images/marx.webp', subject:'economics', bio:'The German philosopher and economist who critiqued capitalism from its foundations. In Capital he developed the labor theory of value and analyzed the mechanisms of exploitation built into capitalist production.', quote:'"The history of all hitherto existing society is the history of class struggles."' },
  { id:'walras', name:'Léon Walras', era:'1834–1910', emoji:'🔢', image:'./images/walras.webp', subject:'economics', bio:'The Swiss economist who founded neo-classical economics. Developed the theory of general equilibrium - the idea that it is possible to describe mathematically how all markets in the economy reach balance simultaneously.', quote:'"Prices are the solution to a system of simultaneous equations."' },
  { id:'sandel', name:'Michael Sandel', era:'1953–', emoji:'🏛️', image:'./images/sandel.webp', subject:'economics', bio:'American political philosopher at Harvard. Known for his critique of capitalism and his argument that there are spheres of life - education, health, democracy - where money should not decide.', quote:'"The market is not a neutral tool - it injects certain values into domains where other values matter more."' },
  { id:'keynes', name:'John Maynard Keynes', era:'1883–1946', emoji:'💰', image:'./images/keynes.webp', subject:'economics', bio:'The British economist who argued that the market does not always correct itself and that governments must spend money during crises.', quote:'"In the long run, we are all dead."' },
  { id:'friedman', name:'Milton Friedman', era:'1912–2006', emoji:'🗽', image:'./images/friedman.webp', subject:'economics', bio:'The American economist from the University of Chicago who argued that the free market is the foundation of human freedom.', quote:'"There\'s no such thing as a free lunch."' },
  { id:'sen', name:'Amartya Sen', era:'1933–', emoji:'🌍', image:'./images/sen.webp', subject:'economics', bio:'The Indian economist and Nobel laureate who argued that real development is not GDP growth but the expansion of people\'s capabilities.', quote:'"Development is freedom."' },
  { id:'jevons', name:'William Stanley Jevons', era:'1835–1882', emoji:'💎', image:'./images/jevons.webp', subject:'economics', bio:'The English economist who discovered "marginal utility" - that value comes not from labor, but from the desire for the next unit.', quote:'"Value is a subjective relation that a person attributes to a thing."' },
  { id:'marshall', name:'Alfred Marshall', era:'1842–1924', emoji:'✂️', image:'./images/marshall.webp', subject:'economics', bio:'The British economist who united supply and demand into one diagram - and laid the foundation for modern economics.', quote:'"We might as well dispute whether it is the upper or the under blade of a pair of scissors that cuts a piece of paper. But it is clear that both blades are needed."' },
  { id:'kahneman', name:'Daniel Kahneman', era:'1934–2024', emoji:'🧠', image:'./images/kahneman-econ.webp', images:{ economics:'./images/kahneman-econ.webp', psychology:'./images/kahneman-psy.webp' }, subject:'economics', subjects:['economics','psychology'], bio:'The Israeli-American psychologist who won the Nobel Prize in Economics in 2002 for revealing the cognitive biases that influence economic decisions.', quote:'"A loss of $100 is felt about twice as strongly as a gain of $100."' },
  { id:'ricardo', name:'David Ricardo', era:'1772–1823', emoji:'🌾', image:'./images/ricardo.webp', subject:'economics', bio:'The British economist who formulated the law of diminishing marginal returns and the theory of income distribution between classes.', quote:'"As more and more labor is added to the same quantity of land - the additional unit of labor will add less production than the previous one."' },
  { id:'piketty', name:'Thomas Piketty', era:'1971–', emoji:'📊', image:'./images/piketty.webp', subject:'economics', bio:'The French economist who measured capital over 300 years, and discovered the formula r > g - the rate of return on capital is always greater than the rate of growth.', quote:'"When the rate of return on capital significantly exceeds the growth rate of the economy - inherited wealth grows faster than the entire economy."' },
  { id:'aquinas', name:'Thomas Aquinas', era:'1225–1274', emoji:'✝️', image:'./images/aquinas.webp', subject:'economics', bio:'A Dominican friar and medieval philosopher who formulated the idea of "the just price," and declared that not everything legal in the market is just.', quote:'"To sell something for more than its real value is a sin, even if no law forbids it."' },
  { id:'pareto', name:'Vilfredo Pareto', era:'1848–1923', emoji:'⚖️', image:'./images/pareto.webp', subject:'economics', bio:'The Italian economist who tried to separate economics from moral questions, and formulated the concept of "Pareto efficiency" which became the foundation of modern economics.', quote:'"An economic state is optimal when it is impossible to improve the welfare of one person without reducing the welfare of another."' },
  { id:'rawls', name:'John Rawls', era:'1921–2002', emoji:'⚖️', image:'./images/rawls.webp', subject:'economics', bio:'The American philosopher who formulated "the veil of ignorance," a thought experiment that tries to define a just society without knowing what your position in it will be.', quote:'"Only behind a veil of ignorance can we choose true principles of justice."' },
  { id:'nozick', name:'Robert Nozick', era:'1938–2002', emoji:'🗽', image:'./images/nozick.webp', subject:'economics', bio:'The American libertarian philosopher who formulated "justice as entitlement" as a response to Rawls: justice is measured by process, not by outcome.', quote:'"A just situation is any situation that was achieved through just means."' },
  { id:'hayek', name:'Friedrich Hayek', era:'1899–1992', emoji:'🌬️', image:'./images/hayek.webp', subject:'economics', bio:'The Austrian-British economist who argued that the concept of "social justice" is meaningless: the outcome of a spontaneous process cannot be called "just" or "unjust."', quote:'"Justice can be a property of human behavior, but not of a state that no one intentionally created."' },
  // Psychology thinkers
  { id:'wundt',   name:'Wilhelm Wundt',    era:'1832–1920', emoji:'🧪', image:'./images/wundt.webp',   subject:'psychology', bio:'The German psychologist who founded the world\'s first psychological laboratory, in Leipzig in 1879. Declared that the mind is a subject for scientific inquiry - not for philosophical speculation. His method was abandoned; his idea still rules.',                                                                                                                                                                            quote:'"The book which I here present to the public is an attempt to mark out a new domain of science."' },
  { id:'james',   name:'William James',    era:'1842–1910', emoji:'🌊', image:'./images/james.webp',   subject:'psychology', bio:'An American philosopher-psychologist at Harvard. Argued against Wundt that consciousness is not a chain of discrete moments - it is a river. Coined the term "stream of consciousness" and founded functional psychology: not what consciousness is made of, but what it does.',                                                                                                                                    quote:'"Consciousness does not appear to itself chopped up in bits. It is nothing jointed - it flows."' },
  { id:'freud',   name:'Sigmund Freud',    era:'1856–1939', emoji:'🛋', image:'./images/freud.webp',   subject:'psychology', bio:'An Austrian physician from Vienna who invented psychoanalysis in the late 19th century. Discovered that most mental activity happens beneath the surface, in the unconscious, shaping every conscious act. Overturned the Western picture of the self.',                                                                                                                                                             quote:'"The division of the psychical into what is conscious and what is unconscious is the fundamental premise of psycho-analysis."' },
  { id:'jung',    name:'Carl Gustav Jung', era:'1875–1961', emoji:'🌀', image:'./images/jung.webp',    subject:'psychology', bio:'A Swiss psychologist, Freud\'s senior student and later his rival. Argued that beneath the personal unconscious lies a collective unconscious - a layer shared by all humans, holding archetypes that recur across myths, dreams, and stories in every culture.',                                                                                                                                                    quote:'"In addition to our immediate consciousness, there exists a second psychic system of a collective, universal, and impersonal nature which is identical in all individuals."' },
  { id:'skinner', name:'B. F. Skinner',    era:'1904–1990', emoji:'🐦', image:'./images/skinner.webp', subject:'psychology', bio:'An American psychologist at Harvard who led the radical-behaviorist revolution. Argued that all talk of an inner "mind" is empty speculation - psychology can only be a science if it measures observable behavior and its consequences: reinforcements and punishments.',                                                                                                                                                quote:'"A person does not act upon the world, the world acts upon him."' },
  { id:'rogers',  name:'Carl Rogers',      era:'1902–1987', emoji:'🌱', image:'./images/rogers.webp',  subject:'psychology', bio:'An American psychologist, founder of humanistic psychology. Rejected both Freud (who saw the person as a victim of repressed drives) and Skinner (who saw a biological machine) - and argued that the person is the subject of their own life, with an inner tendency to grow when given the right conditions.',                                                                                                     quote:'"It is perhaps best conceptualized as a tendency toward fulfillment, toward actualization, involving not only the maintenance but also the enhancement of the organism."' },
  // Psychology chapter 2 — "What drives us?"
  { id:'adler',   name:'Alfred Adler',     era:'1870–1937', emoji:'⬆️', image:'./images/adler.webp',    subject:'psychology', bio:'An Austrian psychologist, once close to Freud and later his rival. Headed the Vienna Psychoanalytic Society until his stormy departure in 1911. Argued that the hidden engine of a person is not sexual but the wish to stop feeling small - what he called "the striving for superiority".',                                                                                                                              quote:'"To be human means to feel inferior, which presses ceaselessly toward its own conquest."' },
  { id:'maslow',  name:'Abraham Maslow',   era:'1908–1970', emoji:'🔺', image:'./images/maslow.webp',   subject:'psychology', bio:'An American psychologist who sought to explain why the same person wants different things at different stages of life. Ordered human needs into an ascending pyramid, from what is necessary for life up to self-actualization, and argued that a need that is satisfied ceases to motivate.',                                                                                                                            quote:'"What a man can be, he must be."' },
  { id:'frankl',  name:'Viktor Frankl',    era:'1905–1997', emoji:'✡️', image:'./images/frankl.webp',   subject:'psychology', bio:'A Viennese psychiatrist who survived the Nazi death camps. Developed logotherapy, "the third Viennese school," and argued that the deepest engine of a person is not drive-satisfaction or the wish for power - but the search for meaning.',                                                                                                                                                                             quote:'"Everything can be taken from a man but one thing: the last of the human freedoms, to choose one\'s attitude in any given set of circumstances."' },
  { id:'fromm',   name:'Erich Fromm',      era:'1900–1980', emoji:'🕊️', image:'./images/fromm.webp',    subject:'psychology', bio:'A German-Jewish psychoanalyst who fled Nazi Germany for the United States. Turned the question upside down: if freedom is so precious, why do people give it up willingly? Showed that freedom can be a burden, and that the modern person buys relief at the price of autonomy.',                                                                                                                                          quote:'"Freedom, though it has brought him independence and rationality, has made him isolated and, thereby, anxious and powerless."' },
  { id:'deci',    name:'Edward Deci',      era:'1942–',     emoji:'🎯', image:'./images/deci.webp',     subject:'psychology', bio:'An American psychologist who studied motivation in the laboratory. Discovered with Ryan that external reward for a task one loves actually pushes the reason for action from within to without, and later identified three basic needs: autonomy, competence, and relatedness.',                                                                                                                                          quote:'"Instead of asking how I can motivate people, we should ask how to create the conditions in which people will motivate themselves."' },
  // Psychology chapter 3 — "Where does who I am come from?"
  { id:'bowlby',    name:'John Bowlby',       era:'1907–1990', emoji:'🔗', image:'./images/bowlby.webp',    subject:'psychology', bio:'A British psychiatrist and psychoanalyst, founder of attachment theory. Worked with children who grew up in institutions after World War II, and discovered that a stable bond with a caregiving figure in the first two years shapes the pattern of relationships across life. Turned "the need for mother" from indulgence into biology.',                                                                             quote:'"Intimate attachments to other human beings are the hub around which a person\'s life revolves, not only when he is an infant or a toddler, but throughout his adolescence and his years of maturity as well, and on into old age."' },
  { id:'winnicott', name:'D. W. Winnicott',   era:'1896–1971', emoji:'🧸', image:'./images/winnicott.webp', subject:'psychology', bio:'A British pediatrician and psychoanalyst. Proposed the concept of the "good-enough mother," needed by the child not through perfection but through measured failure at the right time. The small failure is what enables the child to develop the capacity to cope alone.',                                                                                                                                              quote:'"The good-enough mother starts off with an almost complete adaptation to her infant\'s needs, and as time proceeds she adapts less and less completely, gradually, according to the infant\'s growing ability to deal with her failure."' },
  { id:'erikson',   name:'Erik Erikson',      era:'1902–1994', emoji:'🪜', image:'./images/erikson.webp',   subject:'psychology', bio:'A German-American developmental psychologist. Extended Freud in one decisive direction: psychological shaping does not end in childhood. Proposed eight life stages, from birth to old age, each carrying a crisis to resolve. Whoever does not resolve a crisis carries it forward.',                                                                                                                                    quote:'"Healthy children will not fear life if their elders have integrity enough not to fear death."' },
  { id:'kohut',     name:'Heinz Kohut',       era:'1913–1981', emoji:'👁️', image:'./images/kohut.webp',     subject:'psychology', bio:'An American psychoanalyst born in Vienna, founder of self psychology. Argued that the self is not built from internal validation but from being seen in another person\'s eyes. "The gleam in the parent\'s eye" is the basic condition for developing a sense of worth.',                                                                                                                                               quote:'"The gleam in the mother\'s eye, which mirrors the child\'s exhibitionistic display."' },
  { id:'bandura',   name:'Albert Bandura',    era:'1925–2021', emoji:'🎭', image:'./images/bandura.webp',   subject:'psychology', bio:'A Canadian-American psychologist at Stanford. Showed that a person learns not only through conditioning, but mainly through observing others. The 1961 Bobo doll experiment proved that children imitate the violence they saw in an adult. Proposed the third model after Freud and Skinner: not drives, not reinforcements, but social learning.',                                                                     quote:'"Learning would be exceedingly laborious, not to mention hazardous, if people had to rely solely on the effects of their own actions to inform them what to do. Fortunately, most human behavior is learned observationally through modeling."' },
  // Psychology chapter 4 — "Why are we locked into patterns?"
  { id:'klein',        name:'Melanie Klein',        era:'1882–1960', emoji:'🪆', image:'./images/klein.webp',        subject:'psychology', bio:'A Vienna-born, London-based psychoanalyst. Pioneer of child psychoanalysis through play. Developed object relations theory: we absorb inside us figures of the important people in our lives, and they continue to operate within us for decades after.',                                                                                                                                                                                     quote:'"Gratitude is closely bound up with trust in good figures. Through processes of projection and introjection, through inner wealth given out and taken back in, an enrichment and deepening of the ego takes place."' },
  { id:'anna-freud',   name:'Anna Freud',           era:'1895–1982', emoji:'🛡️', image:'./images/anna-freud.webp',   subject:'psychology', bio:'A Vienna-born psychoanalyst, Sigmund Freud\'s youngest daughter and a psychoanalyst in her own right. Turned the spotlight from the drives to the ego, and mapped an entire system of defense mechanisms, automatic strategies the mind activates in order to keep anxiety at a distance.',                                                                                                                                                     quote:'"This book is concerned with one problem only: the ways and means by which the ego wards off unpleasure and anxiety, and exercises control over impulsive behavior, affects and instinctive urges."' },
  { id:'beck',         name:'Aaron Beck',           era:'1921–2021', emoji:'💭', image:'./images/beck.webp',         subject:'psychology', bio:'An American psychiatrist trained as a psychoanalyst who discovered in the clinic a new phenomenon: between the event and the emotion passes a fast thought, almost imperceptible. Developed cognitive therapy (CBT), which became the most-researched treatment for depression and anxiety, and placed psychotherapy on an empirical footing.',                                                                                              quote:'"Cognitive therapy seeks to alleviate psychological stresses by correcting faulty conceptions and self-signals. By correcting erroneous beliefs we can lower excessive reactions."' },
  { id:'van-der-kolk', name:'Bessel van der Kolk',  era:'1943–',     emoji:'🫀', image:'./images/van-der-kolk.webp', subject:'psychology', bio:'A Dutch-American psychiatrist and trauma researcher. Showed that trauma is not only a memory of an event, but an imprint it leaves on the body and on its alarm system. His book "The Body Keeps the Score" became an enormous bestseller, and at the same time also controversial in the scientific community.',                                                                                                                             quote:'"Trauma is not just an event that took place sometime in the past; it is also the imprint left by that experience on mind, brain, and body. This imprint has ongoing consequences for how the human organism manages to survive in the present."' },
];
